# Generated by Django 5.2.1 on 2025-05-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_snippet_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
